# -*- coding: utf-8 -*-
"""Linear Regression Deployment on streamLit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X1VJGfFofHO5mMV-ohidfL3mrN_Jj8a
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression

# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="House Price Prediction",
    page_icon="🏠",
    layout="centered"
)

st.title("🏠 House Price Prediction")
st.write("Predict house price using Linear Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("houseprice.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X = df.drop("price", axis=1)
y = df["price"]

model = LinearRegression()
model.fit(X, y)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter House Area")

area = st.number_input(
    "Area (Square Feet)",
    min_value=100,
    max_value=10000,
    value=3300,
    step=100
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Price"):

    prediction = model.predict([[area]])

    st.success(f"Predicted Price: ₹ {prediction[0]:,.2f}")

# -----------------------------------
# Model Information
# -----------------------------------
st.subheader("Model Details")

st.write("Coefficient:", model.coef_[0])
st.write("Intercept:", model.intercept_)